//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DelightDiscount
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserLevel
    {
        public long Id { get; set; }
        public string CID { get; set; }
        public Nullable<int> LEVEL1 { get; set; }
        public string LEVEL1STATUS { get; set; }
        public Nullable<int> LEVEL2 { get; set; }
        public string LEVEL2STATUS { get; set; }
        public Nullable<int> LEVEL3 { get; set; }
        public string LEVEL3STATUS { get; set; }
        public Nullable<int> LEVEL4 { get; set; }
        public string LEVEL4STATUS { get; set; }
        public Nullable<int> LEVEL5 { get; set; }
        public string LEVEL5STATUS { get; set; }
        public Nullable<int> LEVEL6 { get; set; }
        public string LEVEL6STATUS { get; set; }
        public Nullable<int> LEVEL7 { get; set; }
        public string LEVEL7STATUS { get; set; }
    }
}
