//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DelightDiscount
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserInfo
    {
        public long Id { get; set; }
        public string AutoUserID { get; set; }
        public string CID { get; set; }
        public string Password { get; set; }
        public string UseName { get; set; }
        public string FullName { get; set; }
        public string PresentAddress { get; set; }
        public string ParmanentAddress { get; set; }
        public string EmailAddress { get; set; }
        public string Mobile { get; set; }
        public string NomineeName { get; set; }
        public string Relation { get; set; }
        public string NomineeMobile { get; set; }
        public string ReferenceCid { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<double> SpotInCome { get; set; }
        public Nullable<double> LevelIncome { get; set; }
        public Nullable<double> AutoIncome { get; set; }
        public Nullable<int> CurrentLevel { get; set; }
        public string IsActive { get; set; }
        public byte[] UserPic { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
