//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DelightDiscount
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserSpotTrack
    {
        public long Id { get; set; }
        public string CID { get; set; }
        public string PID { get; set; }
        public string SID { get; set; }
        public string IsAvailable { get; set; }
        public string UCID { get; set; }
        public Nullable<int> SlTrk { get; set; }
    }
}
