//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DelightDiscount
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LevelCount
    {
        public long Id { get; set; }
        public string CID { get; set; }
        public Nullable<int> TotalSpot { get; set; }
        public Nullable<int> LevelStatus { get; set; }
        public string IsComplete { get; set; }
        public string IsPaid { get; set; }
    }
}
